### ISSUE TITLE
undefined method `attribute_condition' for #<Class:0x000000048ba9f8>

### ISSUE THREAD

**Issue by lesyk** [ryanb/cancan#822]
After updating gem to 1.6.9 appeared next issue in abilities.rb in line:

can :manage, Upload, :company_id => user.company_id

attribute "company_id" can't be called to Upload model
