### ISSUE TITLE
undefined method `slice' for :project:Symbol

### ISSUE THREAD

**Issue by lhoBas** [ryanb/cancan#112]
Hi,

After upgrading to CanCan 1.3 it starts to throw slicing errors at me... Kind of afraid now ;)

The error:
    ActionController::RoutingError (undefined method `slice' for :project:Symbol):
    app/controllers/invites_controller.rb:2

My controller:
    class InvitesController < ApplicationController
      load_and_authorize_resource :project
      load_and_authorize_resource :invite, :through => :project

Changed it to the new syntax. Worked fine with the old syntax on 1.2.

Using Rails 3 RC, ruby 1.8.7 (2009-06-12 patchlevel 174) [i686-darwin10.3.0]
