### ISSUE TITLE
CanCan 2.0 - Passing array of actions into can? method

### ISSUE THREAD

**Issue by fran-worley** [ryanb/cancan#798]
I have just added the 2.0 version of the gem into my rails app and noticed that 

```
if can? [:update, :destroy], :users
```

which used to work fine in 1.6.8 now causes the error: 

```
undefined method `to_sym' for [:update, :destroy]:Array
```

is this something that has been removed or is it something which isn't yet working?

for now I will replace my code with 

```
if can?(:update, :users) && can?(:destroy, :users)
```

but it just seems a little messy in comparison.
